name: azaFashions
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  webengage_flutter: 1.0.2
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  firebase_core:
  firebase_analytics: ^8.0.4
  cupertino_icons: ^0.1.3
  provider: ^5.0.0
  flutter_platform_widgets: ^0.50.0
  smooth_star_rating: ^1.0.4+2
  rxdart: ^0.24.1
  page_view_indicators: ^1.3.1
  carousel_slider: ^2.1.0
  flutter_staggered_grid_view: ^0.3.0
  shared_preferences: 2.0.5 #^0.5.7+3
  connectivity: ^3.0.3 #^0.4.8+6
  fluttertoast: ^4.0.1
  intl: ^0.17.0
  flutter_launcher_icons: ^0.9.0
  http: ^0.13.1
  device_id: #^0.2.0
  cached_network_image: ^2.5.1 #^2.2.0+1
  geolocator: #^5.3.2+2
  geocoder: ^0.2.1
  location:  ^4.1.1 #^3.0.2
  percent_indicator: ^2.1.5
  firebase_dynamic_links: ^0.5.1
  url_launcher: #^5.4.11
  device_preview: ^0.7.1
  countdown: ^0.1.0
  google_sign_in: ^4.5.1
  firebase_auth: ^1.0.1
  flutter_facebook_login: ^3.0.0
  flutter_range_slider: ^1.4.0
  grouped_list: ^3.3.0
  scrollable_positioned_list: ^0.1.7
  scroll_to_index: ^1.0.6
  flutter_webview_plugin: ^0.3.11
  webview_flutter: ^2.0.4
  flutter_rating_bar: ^3.2.0+1
  badges: ^1.1.6
  hexcolor: ^1.0.4
  custom_switch: ^0.0.1
  scroll_bars_common: ^2.0.0
  intl_phone_number_input: ^0.7.0     #^0.6.0
  photo_view: ^0.10.3
  country_codes:
  pin_code_fields: ^6.1.0
  crypto: ^3.0.0 #^2.1.5
  device_info: ^0.4.0+4
  country_code_picker: ^1.7.0
  share:
  firebase_crashlytics: ^2.0.0
  devicelocale: ^0.4.1
  currency_pickers: ^1.0.6
  flutter_html:
  store_redirect: ^1.0.2
  apple_sign_in: ^0.1.0
  launch_review: ^3.0.1




flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/azalogo.png"






dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/splash_aza_logo.png
    - images/hanger.png
    - images/whatsapp.png
    - images/similarproducts_icon.png
    - images/wishlist_icon.png
    - images/sort.png
    - images/shipping_banner.png
    - images/frontBodyMeasurement.png
    - images/share.png
    - images/home_active_icon.png
    - images/categories.png
    - images/profile_icon.png
    - images/notification_icon.png
    - images/facebook.png
    - images/google.png
    - images/cart_icon.png
    - images/indianFlag.png
    - images/aza.png
    - images/azalogo.png
    - images/under_maintenance.png
    #added by Ajay
    - images/no_internet.png
    - images/empty_bag.png
    - images/empty_wishlist.png
    - images/no_notification.png
    - images/apple.png






  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: fontfamily/PlayfairDisplay-Regular.ttf

    - family: Roboto
      fonts:
        - asset:  fontfamily/Roboto-Regular.ttf

    - family: Helvetica
      fonts:
        - asset:  fontfamily/Helvetica-Condensed.ttf



  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
